### ISSUE TITLE
Watchbox-Plugin funktioniert nicht mehr (kann keine Videos Streamen) [gelöst]

### ISSUE THREAD

**Issue by Martin1995** [MrKrabat/plugin.video.watchbox#2]
Heute habe ich festgestellt dass das Watchbox-Plugin keine Videos mehr von Watchbox streamt. Ich weis jetzt nicht ob es nur ein Problem bei mir gibt oder ob es mit Watchbox zu tun hat. Eventuell kannste mir Helfen das Problem zu finden. 
Im Anhang ein ausschnitt des Logs mit den Fehlern.

Danke schon mal im Voraus für die Hilfe
[kodi.log.snapshot.txt](https://github.com/MrKrabat/plugin.video.watchbox/files/1958115/kodi.log.snapshot.txt)

**Comment by MrKrabat** [comment]
ich habe das Problem zusammen mit ein paar anderen heute bereits behoben.
Kannst du einmal die Version ausprobieren hier im Github?

**Comment by Martin1995** [comment]
Wie installiere ich die Version von GitHub?

**Comment by Martin1995** [comment]
Gerade die Antwort wegen Installation gefunden....
google findet ja fast alles

**Comment by Martin1995** [comment]
Ja die neue Version von GitHub behebt den Fehler

DANKE
