### ISSUE TITLE
Drm bug ???

### ISSUE THREAD

**Issue by golle15** [MrKrabat/plugin.video.watchbox#4]
hey nochmal, 

neu erscheinung findest du unter anime - blade gibt noch einige mehr die darunter leiden 

hast du dafür auch eine lösung

02:35:10.854 T:139635282172096  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.watchbox/?fanart=https%3A%2F%2Faiswatchbox-a.akamaihd.net%2Fwatchbox%2Fformat%2F15767_dvdcover%2F484x677%2Fblade.jpg&episode=1&thumb=https%3A%2F%2Faiswatchbox-a.akamaihd.net%2Fwatchbox%2Fmovie%2F414272%2F495x278%2Fsein-name-ist-blade.jpg&title=1+-+Sein+Name+ist+Blade&url=%2Fserien%2Fblade-15767%2Fstaffel-1%2Fsein-name-ist-blade-414272.html&season=1&duration=1320&mode=videoplay&plot=Blade+ist+halb+Mensch%2C+halb+Vampir+und+k%C3%A4mpft+gegen+die+bedrohlichen+Vampirwesen.+Seine+Reise+nach+S%C3%BCdostasien+beschreitet+er+mit+dem+Ziel+die+Rache+an+Deacon+Frost%2C+dem+Vampir-Lord%2C+auszu%C3%BCben.&plotoutline=Die+Marvel+Adaption+zum+Daywalker+Blade+-+Halb+Mensch%2C+halb+Vampir%21&year=2011
02:35:10.863 T:139634700994304  NOTICE: Creating InputStream
02:35:10.864 T:139634700994304  NOTICE: Creating Demuxer
02:35:12.859 T:139634700994304   ERROR: OpenDemuxStream - Error creating demuxer
02:35:12.860 T:139634700994304  NOTICE: CVideoPlayer::OnExit()

**Comment by MrKrabat** [comment]
Ich hab derzeit nicht viel Zeit dafür, aber was ich mir angeguckt habe sieht sehr schlecht aus für Kodi.

Deren DRM Eigenentwicklung liefert auf unkonventionelle Art einen Key mit zum Entschlüsseln, aber Kodi und auch Inputstream.Adaptive erwarten, dass ein License-Server den Key ausgibt, da dies Standard ist. Sprich es gibt gar keine Schnittstelle wo ich manuell den Key rein werfen kann.

Sieht erstmal sehr schlecht aus für die Zukunft, ich werde wohl mal Inputstream.Adaptive anpingen, aber selbst wenn die eine Schnittstelle zaubern würde die nur auf den neusten Kodi 18 Alpha Builds implementiert werden :/

**Comment by MrKrabat** [comment]
Okay Update:
DRM ist implementiert und es läuft nun!

Die alten Folgen laufen derzeit noch wie gewohnt über HLS ohne DRM. Die Folgen welche DRM haben laufen über MPEG+DASH mit Widevine DRM. Dies erfordert, dass die Widevine Bibliothek installiert ist.

script.module.inputstreamhelper übernimmt diesen Job automatisch, andere Addons wie Netflix nutzen das ebenfalls :)

**Comment by golle15** [comment]
Viel Dank, das ging echt fix und läuft.

Das Problem mit DRM und Kodi ist bekannt :-/ die Entwickler sind aber auf gutem Weg. 
Die nightly build hab ich installiert :-)

bekomme jetzt jedoch beim playback mit DRM einen ERROR: OpenDemuxStream - Error creating demuxer hin und wieder. das ist jedoch nicht dein Problem mit dem addon, sondern eines von Kodi. denk das werden sie auch hinbekommen mit der Zeit :-)

großartige arbeit von dir

**Comment by MrKrabat** [comment]
hmm eigentlich sollte der Playback gehen (auch mit Kodi 17 in der Theorie).

Für mich sieht es aus als hätte script.module.inputstreamhelper derzeit Probleme, aber das wird hoffentlich bald gefixt, Pull requests sehe ich bereits bei denen :)
